# Generated by Django 5.2.6 on 2025-09-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='내용')),
                ('device_name', models.CharField(blank=True, max_length=50, verbose_name='장비명')),
                ('assignee', models.CharField(blank=True, max_length=50, verbose_name='CS담당자')),
                ('customer_name', models.CharField(blank=True, max_length=50, verbose_name='고객명')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('MED', '보통'), ('HIGH', '높음')], default='MED', max_length=4, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('NEW', '신규'), ('INP', '처리중'), ('RES', '해결'), ('CLS', '종료')], default='NEW', max_length=3, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
